# Generated by Django 2.2.19 on 2021-04-06 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.IntegerField(null=True)),
                ('account_banned', models.BooleanField(default=False)),
                ('otp_time', models.DateTimeField(default=datetime.datetime(2021, 4, 6, 7, 55, 21, 271753))),
                ('otp', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
