# Generated by Django 2.2.19 on 2021-04-06 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210406_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signup_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 8, 10, 9, 339022)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 8, 10, 9, 338972)),
        ),
    ]
