# Generated by Django 2.2.19 on 2021-04-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodation_code', models.IntegerField(default=0)),
                ('refund_percentage', models.FloatField(default=95.0, null=True)),
                ('no_refund_time', models.IntegerField(default=60)),
                ('min_refund_time', models.IntegerField(default=720)),
                ('addition_deduction_percentage', models.FloatField(default=1.0, null=True)),
                ('addition_deduction_rate', models.IntegerField(default=30)),
            ],
        ),
    ]
