# Generated by Django 2.2.19 on 2021-04-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('city', models.CharField(max_length=1000, null=True)),
                ('state', models.CharField(max_length=1000, null=True)),
                ('terminal_code', models.CharField(max_length=1000, null=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='busdetails',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
