# Generated by Django 2.2.19 on 2021-04-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210406_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('RTO_number', models.CharField(max_length=20, null=True)),
                ('seats', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.BusDetails')),
            ],
        ),
    ]
