# Generated by Django 2.2.19 on 2021-04-06 11:26

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_busschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 16, 56, 45, 889126)),
        ),
        migrations.CreateModel(
            name='DateWiseBusSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField(default=datetime.datetime(2021, 4, 6, 16, 56, 45, 889765))),
                ('seats_opted', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=100)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.BusSchedule')),
            ],
        ),
    ]
