# Generated by Django 2.2.19 on 2021-04-06 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210407_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetail',
            name='multiplier',
            field=models.FloatField(default=0.1, null=True),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 1, 45, 17, 33772)),
        ),
        migrations.AlterField(
            model_name='datewisebusschedule',
            name='departure_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 1, 45, 17, 34344)),
        ),
    ]
