# Generated by Django 2.2.19 on 2021-04-07 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210407_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datewisebusschedule',
            name='seats_opted',
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 10, 2, 55, 764028)),
        ),
        migrations.AlterField(
            model_name='datewisebusschedule',
            name='departure_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 10, 2, 55, 764983)),
        ),
    ]
