# Generated by Django 2.2.19 on 2021-04-09 01:07

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210408_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='datewisebusschedule',
            name='seats_opted',
            field=django_mysql.models.ListTextField(models.IntegerField(default=0), default=[], size=100000),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.TimeField(default=datetime.time(6, 37, 38, 256901)),
        ),
        migrations.AlterField(
            model_name='datewisebusschedule',
            name='departure_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 6, 37, 38, 257477)),
        ),
    ]
