# Generated by Django 2.2.19 on 2021-04-09 01:14

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210409_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.TimeField(default=datetime.time(6, 44, 29, 442184)),
        ),
        migrations.AlterField(
            model_name='datewisebusschedule',
            name='departure_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 6, 44, 29, 442764)),
        ),
        migrations.AlterField(
            model_name='datewisebusschedule',
            name='seats_opted',
            field=django_mysql.models.ListTextField(models.IntegerField(default=0), default=[0, 0], size=100000),
        ),
    ]
