# Generated by Django 2.2.19 on 2021-04-09 01:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210409_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.TimeField(default=datetime.time(7, 26, 59, 374594)),
        ),
        migrations.AlterField(
            model_name='stop',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Schedule'),
        ),
    ]
