# Generated by Django 2.2.19 on 2021-04-09 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20210409_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticket',
            name='date_of_booking',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 11, 47, 43, 999093)),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.TimeField(default=datetime.time(11, 47, 43, 994130)),
        ),
    ]
