# Generated by Django 2.2.19 on 2021-04-10 08:52

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210409_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='datewisebusschedule',
            name='stop_id',
            field=django_mysql.models.ListTextField(models.IntegerField(default=0), default=[0, 0], size=100000),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.TimeField(default=datetime.time(14, 22, 31, 174535)),
        ),
        migrations.AlterField(
            model_name='datewisebusschedule',
            name='departure_date',
            field=models.DateField(default=datetime.date(2021, 4, 10)),
        ),
        migrations.AlterField(
            model_name='userticket',
            name='date_of_booking',
            field=models.DateField(default=datetime.datetime(2021, 4, 10, 14, 22, 31, 177387)),
        ),
    ]
