# Generated by Django 2.2.19 on 2021-04-11 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210410_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticket',
            name='refund_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.TimeField(default=datetime.time(22, 24, 22, 452396)),
        ),
        migrations.AlterField(
            model_name='datewisebusschedule',
            name='departure_date',
            field=models.DateField(default=datetime.date(2021, 4, 11)),
        ),
        migrations.AlterField(
            model_name='userticket',
            name='date_of_booking',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 22, 24, 22, 455345)),
        ),
    ]
