# Generated by Django 2.2.19 on 2021-04-14 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210411_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.TimeField(default=datetime.time(9, 59, 37, 914498)),
        ),
        migrations.AlterField(
            model_name='datewisebusschedule',
            name='departure_date',
            field=models.DateField(default=datetime.date(2021, 4, 14)),
        ),
        migrations.AlterField(
            model_name='userticket',
            name='date_of_booking',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 9, 59, 37, 917593)),
        ),
    ]
