# Generated by Django 3.0.8 on 2021-04-24 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20210414_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.TimeField(default=datetime.time(15, 47, 12, 313868)),
        ),
        migrations.AlterField(
            model_name='datewisebusschedule',
            name='departure_date',
            field=models.DateField(default=datetime.date(2021, 4, 24)),
        ),
        migrations.AlterField(
            model_name='userticket',
            name='date_of_booking',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 15, 47, 12, 315738)),
        ),
    ]
